version: '3.7'

services:
  selenium:
    image: selenium/standalone-chrome:4.19.1
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 2g
    volumes:
      - ./shared:/shared

  test-runner:
    build: .
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=http://selenium:4444/wd/hub
    volumes:
      - ./shared:/shared